### PR TITLE
Use `Set` and `Stream#distinct` to prevent duplication

### PR DESCRIPTION
**Pull request by sdreynolds**
Summary:
Today, this implementation will duplicate the unique rows by returning
more than one match per row on the left. By using both
`Stream#distinct`, it reduces the sub scans to only scans that are
unique

Caching implementation -- and bug introduction -- happened here: https://github.com/twilio/calcite-kudu/pull/14

## Bug Description
1. Same `Actor Sid` is used by multiple rows in the batch
2. A Single `CachingEnumerator` is created. It is placed twice in the `List<Enumerator>`
3. First `CachingEnumerator` executes Kudu RPC to get the result, marks `doneScan = true` and closes `actualEnumerator`
4. The second place in the `List<Enumerator>` that points to the same `CachingEnumerator` gets called.  It returns a value from `cachedValues` (because `doneScan` is `true`)
5. Both of the values are added to [`outerValues`](https://github.com/apache/calcite/blob/master/linq4j/src/main/java/org/apache/calcite/linq4j/EnumerableDefaults.java#L1702)
6. [Both results are added to the join](https://github.com/apache/calcite/blob/master/linq4j/src/main/java/org/apache/calcite/linq4j/EnumerableDefaults.java#L1731-L1756)

## Resolution
This takes all the predicates and de dupes them so there is only one element in the `List<Enumerator>`. 

## Another Potential Resolution
For a given `CachingEnumerator`, it operates in one mode if the cache already exists for this scan and another mode -- fill cache and return results mode -- when it doesn't have a cache value for this scan.

**Contributing to Twilio**

> All third-party contributors acknowledge that any contributions they provide will be made under the same open-source license that the open-source project is provided under.

- [X] I acknowledge that all my contributions will be made under the project's license.

### CODE REVIEW

**Comment by sdreynolds** [comment]
Internal test suite passes

**Comment by twdsilva** [comment]
I am trying to understand how we got a duplicate row. Looking at the query that has the incorrect results the we would only have 2 rows on the left side each with a different actor side right ?

**Comment by sdreynolds** [comment]
> I am trying to understand how we got a duplicate row. Looking at the query that has the incorrect results we would only have 2 rows on the left side each with a different actor sid right ?

Updated PR description to describe it and offer an alternative solution as well. Sorry for not doing this properly, I did a "end of the day this worked" PR instead of putting in the effort to explain the change clearly.

**Comment by rbhanot** [comment]
I am onboard the current distinct implementation.
As for the alternate solution, I do not understand how can we prevent `fill cache and return results mode` from happening twice which may be the reason for this as another scan can still be invoked to get the value from DB and distinct seems the only way out.
What I can only push for(hope for or dont know if it is already implemented ) is we are calling distinct on the smaller dimension (right or left) otherwise the distinct can become cumbersome. Dont know if it again illudes to cost estimation dialing into the side we call distinct on.

**Review by twdsilva — APPROVED** [review]

**Comment by sdreynolds** [comment]
> What I can only push for(hope for or dont know if it is already implemented ) is we are calling distinct on the smaller dimension (right or left) otherwise the distinct can become cumbersome. Dont know if it again illudes to cost estimation dialing into the side we call distinct on.

This is calling `Stream#distinct` on the `CalciteKuduPredicates` for the `right` table. Because we don't allow [Joins to commute](https://github.com/twilio/calcite-kudu/blob/main/adapter/src/main/java/com/twilio/kudu/sql/KuduQuery.java#L78-L79), it will be the smaller table

**Pull request merged**
